name: Update gh-pages branch from uptime-status-generator
on:
  workflow_dispatch:
  schedule:
  - cron: '*/59 * * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:

    - name: Check out
      uses: actions/checkout@v2
      with:
        ref: 'gh-pages'

    - name: (GLOBAL) Check out uptime-status-generator repository
      uses: actions/checkout@master
      with:
        token: ${{ secrets.PAT }}
        repository: callruby/uptime-status-generator
        path: uptime-status-generator-gh-pages
        ref: 'gh-pages'
              
    - name: Push Changes
      run: |
        cp -fr uptime-status-generator-gh-pages/* .
        rm -rf uptime-status-generator-gh-pages
        ls -la
        #if [[ -z "$(git status -s -- README.md)" ]] && [[ -z "$(git status -s -- *.md)" ]]; then
        #  echo No changes to commit
        #  exit 0
        #fi
        git status
        git config user.email "check-action@github"
        git config user.name "check-action"
        git add *
        git commit -m "Update all files"
        git push origin gh-pages
